<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book[
    <!ELEMENT book (title,author,isbn,publisher,edition,price)>
    <!ELEMENT  title (#PCDATA)>
    <!ELEMENT  author (#PCDATA)>
    <!ELEMENT  isbn (#PCDATA)>
    <!ELEMENT  publisher (#PCDATA)>
    <!ELEMENT  edition (#PCDATA)>
    <!ELEMENT  price (#PCDATA)>
]>
<book>
    <title>The Pragmatic Programmer</title>
    <author>Andrew Hunt, David Thomas</author>  
    <isbn>978-0135957059</isbn>
    <publisher>Addison-Wesley</publisher>
    <edition>2nd</edition>
    <price>45.99</price>
</book>
